import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SearchInput from "./components/SearchInput";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "PokeSearch",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<div className="flex flex-col gap-5 items-center mt-5">
					<span className="text-2xl">Búsqueda Pokémon</span>
					<SearchInput></SearchInput>
					{children}
				</div>
			</body>
		</html>
	);
}
